---
--- Generated by Luanalysis
--- Created by Thinkpad.
--- DateTime: 2022/7/20 16:54
---

-- 1.1 优惠券id
local vocherId=ARGV[1]
-- 1.2 用户id
local userId=ARGV[2]

-- 2 库存key 拼接 ..
local stockkey= 'seckill:stock'..vocherId

--2.1 订单k
local orderKey='seckill:order'..vocherId
--3库存是否充足
-- redsi返回字符串 需转  数字 tonumber

if (tonumber(redis.call('get',stockkey))<=0) then
    -- 库存不足返回1
    return 1
end

-- 3.2 判断用户是否下单 set 命令 sismember
if (redis.call('sismember',orderKey,userId)==1) then
    -- 3.3 存在 说明是重复下单 返回2
    return 2
end
-- 3.4 口库存 incry-1
redis.call('incrby',stockkey,-1)

--3.5 下单 保存用户
redis.call('sadd',orderKey,userId)

-- 成功返回0
return 0